# Generated by Django 5.2.5 on 2025-08-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
