# Generated by Django 5.2.5 on 2025-08-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
